language: go

services:
- postgresql

go:
  - 1.1
  - 1.2
  - 1.3
  - tip

install:
  - go get gopkg.in/bufio.v1
  - go get github.com/golang/glog
  - go get github.com/go-sql-driver/mysql
  - go get github.com/lib/pq
  - go get launchpad.net/gocheck
  - mkdir -p $HOME/gopath/src/gopkg.in
  - ln -s `pwd` $HOME/gopath/src/gopkg.in/pg.v2

before_script:
  - psql -c 'CREATE DATABASE test;' -U postgres
